version: "3"

services:
  web:
    build: ./api/.
    env_file:
      - .env
    command: python main.py
    networks:
      - api_network
    restart: always

  server:
    build: ./server/.
    volumes:
      - ./server/html_files/:/usr/share/nginx/html
    depends_on:
      - web
    networks:
      - api_network
    ports:
      - 8000:80
    restart: always

networks:
  api_network:
    driver: bridge
