version: "3"

services:
  web:
    build: ./api/.
    environment:
      DEBUG: 1
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    networks:
      - api_network
    restart: always

networks:
  api_network:
    driver: bridge
