version: "3"

services:
  web:
    build: ./api/.
    env_file:
      - .env
    command: python main.py
    ports:
      - 8000:8000
    networks:
      - api_network
    restart: always

networks:
  api_network:
    driver: bridge
